###
POST http://localhost:5000/users/signup/admin
Content-Type: application/json

{
    "firstname": "Saman",
    "lastname": "Perera",
    "email": "admin@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/users/login
Content-Type: application/json

###
GET https://random-data-api.com/api/users/random_user?size=5

###
GET https://run.mocky.io/v3/5e62ad6b-2f4e-4ec8-9073-280b63cb8798